const data = [
  {
    "_id": "6301d01d630d290f217de96f",
    "EIndex": 1464,
    "Competency Name": "Project-related feedback",
    "Sub category": "General",
    "Question": "For a current of recent project, could you please describe your experiences of working on this project? Please try to include both, positive and negative aspect in your answer.",
    "Options": "YN",
    "Option Selection": "Y",
    "Link": null,
    "Link Index": 0,
    "Ranking": "WESY3",
    "Cluster": 4
  },
  {
    "_id": "6301d01d630d290f217de96e",
    "EIndex": 1463,
    "Competency Name": "People-related feedback",
    "Sub category": "General",
    "Question": "Could you please describe your overall impression of your manager's behavior towards you?",
    "Options": "NONE",
    "Option Selection": "Y",
    "Link": null,
    "Link Index": 1462,
    "Ranking": "WESY2",
    "Cluster": 3
  },
  {
    "_id": "6301d01d630d290f217de96a",
    "EIndex": 1462,
    "Competency Name": "People-related feedback",
    "Sub category": "General",
    "Question": "Could you please describe your overall impression of your peer's behavior towards you?",
    "Options": "NONE",
    "Option Selection": "Y",
    "Link": null,
    "Link Index": 0,
    "Ranking": "WESY2",
    "Cluster": 3
  },
  {
    "_id": "6301d01d630d290f217de96d",
    "EIndex": 1461,
    "Competency Name": "Workplace environment-related feedback",
    "Sub category": "General",
    "Question": "In at least 5 words, could you describe at least one aspect of your workplace that you would like to improve or change?",
    "Options": "NONE",
    "Option Selection": "Y",
    "Link": "Link",
    "Link Index": 0,
    "Ranking": "WESY1",
    "Cluster": 2
  },
  {
    "_id": "6301d01d630d290f217de96c",
    "EIndex": 1460,
    "Competency Name": "Overall Job-related feedback",
    "Sub category": "General",
    "Question": "In a few sentences, can you tell us how do you feel about your current job all in all? Please make sure you elaborate as much as you can?",
    "Options": "NONE",
    "Option Selection": "Y",
    "Link": null,
    "Link Index": 1459,
    "Ranking": "WESY5",
    "Cluster": 1
  },
  {
    "_id": "6301d01d630d290f217de96b",
    "EIndex": 1459,
    "Competency Name": "Overall Job-related feedback",
    "Sub category": "General",
    "Question": "In a few sentences, how well do you think is your current compensation and benefits package?",
    "Options": "NONE",
    "Option Selection": "Y",
    "Link": null,
    "Link Index": 1458,
    "Ranking": "WESY4",
    "Cluster": 1
  },
  {
    "_id": "6301d01d630d290f217de96a",
    "EIndex": 1458,
    "Competency Name": "Overall Job-related feedback",
    "Sub category": "General",
    "Question": "In a few sentences, can you tell us how do you feel about the help and supervision that you receive from your line manager and senior managers?",
    "Options": "NONE",
    "Option Selection": "Y",
    "Link": null,
    "Link Index": 1457,
    "Ranking": "WESY3",
    "Cluster": 1
  },
  {
    "_id": "6301d01d630d290f217de96z",
    "EIndex": 1457,
    "Competency Name": "Overall Job-related feedback",
    "Sub category": "General",
    "Question": "In a few sentences, can you describe your relationship with majority of your co-workers and colleagues?",
    "Options": "NONE",
    "Option Selection": "Y",
    "Link": null,
    "Link Index": 1456,
    "Ranking": "WESY2",
    "Cluster": 1
  },
  {
    "_id": "6301d01d630d290f217de96y",
    "EIndex": 1456,
    "Competency Name": "Overall Job-related feedback",
    "Sub category": "General",
    "Question": "In a few sentences, can you provide feedback on the learning and development opportunities for yourself at work?",
    "Options": "NONE",
    "Option Selection": "Y",
    "Link": null,
    "Link Index": 0,
    "Ranking": "WESY1",
    "Cluster": 1
  }
]
module.exports = { data }