const data_v2 = [
  {
    "EIndex": 1464,
    "Competency Name": "Conscientiousness",
    "Sub category": "General",
    "Question": "During the last quarter, has &username drafted time schedules for his tasks and organized action plans for his responsibilities in a timely manner?",
    "Options": "NFMA",
    "Option Selection": "Y",
    "Link": null,
    "Link Index": 0,
    "Ranking": "WESY1",
    "Cluster": 3,
    "Defination": "Allocates time and resources for individual and team objectives and achieves effective levels of productivity targets for the benefit of the organization"
  },
  {
    "EIndex": 1464,
    "Competency Name": "Conscientiousness",
    "Sub category": "General",
    "Question": "During the last quarter, has &username effectively prioritized between critical responsibilities and secondary tasks as well as responsibilities?",
    "Options": "NFMA",
    "Option Selection": "Y",
    "Link": null,
    "Link Index": 0,
    "Ranking": "WESY1",
    "Cluster": 3,
    "Defination": "Allocates time and resources for individual and team objectives and achieves effective levels of productivity targets for the benefit of the organization"
  },
  {
    "EIndex": 1462,
    "Competency Name": "Conscientiousness",
    "Sub category": "General",
    "Question": "During the last quarter, has &username promptly responded to work-related demands and requests?",
    "Options": "NFMA",
    "Option Selection": "Y",
    "Link": "Link",
    "Link Index": 0,
    "Ranking": "WESY2",
    "Cluster": 2,
    "Defination": "Proactively taking initiative towards responsibilities as well as tasks and involving ideas and feedback from others in planning the execution of those responsibilities and tasks"
  },
  {
    "_id": "6301d01d630d290f217de96d",
    "EIndex": 1462,
    "Competency Name": "Conscientiousness",
    "Sub category": "General",
    "Question": "During the last quarter, has &username rejected taking necessary, work-related responsibilities or requests?",
    "Options": "NFMARC",
    "Option Selection": "Y",
    "Link": "Link",
    "Link Index": 0,
    "Ranking": "WESY2",
    "Cluster": 2,
    "Defination": "Proactively taking initiative towards responsibilities as well as tasks and involving ideas and feedback from others in planning the execution of those responsibilities and tasks"

  },
  {
    "_id": "6301d01d630d290f217de96d",
    "EIndex": 1462,
    "Competency Name": "Conscientiousness",
    "Sub category": "General",
    "Question": "During the last quarter, has &username constantly relied upon his peers as well as seniors for direction towards work-related responsibilities and tasks?",
    "Options": "NFMARC",
    "Option Selection": "Y",
    "Link": "Link",
    "Link Index": 0,
    "Ranking": "WESY2",
    "Cluster": 2,
    "Defination": "Proactively taking initiative towards responsibilities as well as tasks and involving ideas and feedback from others in planning the execution of those responsibilities and tasks"

  },
  {
    "_id": "6301d01d630d290f217de96b",
    "EIndex": 1460,
    "Competency Name": "Conscientiousness",
    "Sub category": "General",
    "Question": "During the last quarter, has &username actively defined and clarified his task or project-related short, medium and long term goals?",
    "Options": "NFMA",
    "Option Selection": "Y",
    "Link": "Link",
    "Link Index": 0,
    "Ranking": "WESY3",
    "Cluster": 1,
    "Defination": "Setting as well as achieving high standards of outcome and taking into account the bigger picture involving the goals of the organization when making decisions"
  },
  {
    "_id": "6301d01d630d290f217de96b",
    "EIndex": 1460,
    "Competency Name": "Conscientiousness",
    "Sub category": "General",
    "Question": "During the last quarter, has &username actively prioritized individual goals over team and organization goals?",
    "Options": "NFMARC",
    "Option Selection": "Y",
    "Link": "Link",
    "Link Index": 0,
    "Ranking": "WESY3",
    "Cluster": 1,
    "Defination": "Setting as well as achieveing high standards of outcome and taking into account the bigger picture involving the goals of the organisation when making decisions"
  },
  {
    "_id": "6301d01d630d290f217de969",
    "EIndex": 1458,
    "Competency Name": "Conscientiousness",
    "Sub category": "Leadership",
    "Question": "During the last quarter, has &username undertaken feasibility planning or discussed the feasibility of projects and tasks delegated with his team?",
    "Options": "NFMA",
    "Option Selection": "Y",
    "Link": "Link",
    "Link Index": 0,
    "Ranking": "WESY4",
    "Cluster": 1,
    "Defination": "Setting up controls to foresee  risks regarding responsibilities tasks and decisions, and allowing for creating contingencies when planning"
  },
  {
    "_id": "6301d01d630d290f217de969",
    "EIndex": 1458,
    "Competency Name": "Conscientiousness",
    "Sub category": "Leadership",
    "Question": "During the last quarter, has &username provided or discussed a general schedule or timeline of new projects and tasks within his team?",
    "Options": "NFMA",
    "Option Selection": "Y",
    "Link": "Link",
    "Link Index": 0,
    "Ranking": "WESY4",
    "Cluster": 1,
    "Defination": "Setting up controls to foresee  risks regarding responsibilities tasks and decisions, and allowing for creating contingencies when planning"
  },
]

module.exports = { data_v2 }