const swaggerAutogen = require('swagger-autogen')()
const path = require('path')
const outputFile = path.join(__dirname, '/public/swagger_output.json')
const endpointsFiles = ['./routes/*.route.js']
const doc = {
  info: {
    version: "1.0.0",
    title: "TalentSpotify API Documentation",
    description: "Documentation automatically generated by the <b>swagger-autogen</b> module.",
    contact: {
      name: "TalentSpotify",
      url: "https://talentspotify.com/"
    }
  },
  host: "talent-spotify-backend-git-common-dev-talentspotify.vercel.app",
  basePath: "/api",
  schemes: ['https', 'http'],
  consumes: ['application/json'],
  produces: ['application/json'],
  securityDefinitions: {
    api_key: {
      type: "apiKey",
      name: "api_key",
      in: "header"
    },
    petstore_auth: {
      type: "oauth2",
      authorizationUrl: "https://petstore.swagger.io/oauth/authorize",
      flow: "implicit",
      scopes: {
        read_pets: "read your pets",
        write_pets: "modify pets in your account"
      }
    }
  }

}

swaggerAutogen(outputFile, endpointsFiles, doc)